"""empty message

Revision ID: bc6c5e4ba600
Revises: 34a1b5857b14
Create Date: 2020-08-31 10:22:41.543463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc6c5e4ba600'
down_revision = '34a1b5857b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('description', sa.String(length=250), nullable=True))
    op.drop_column('Venue', 'seeking_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_description', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'description')
    # ### end Alembic commands ###
